### ISSUE TITLE
thread 'main' panicked at 'BindGroupDescriptor is not generic'

### ISSUE THREAD

**Issue by DevOrc** [eqrion/cbindgen#573] opened 2020-09-20 19:24 UTC
Version: 0.14.5
Rust:  Rust 1.46 Stable / Rust Nightly

```
thread 'main' panicked at 'BindGroupDescriptor is not generic', ... \cbindgen-0.14.5\src\bindgen\ir\structure.rs:369:9
```

See CI Build: https://github.com/DevOrc/wgpu-native/runs/1140985652?check_suite_focus=true

__Reproduce:__
Run `make ffi/wgpu.h` on https://github.com/DevOrc/wgpu-native/tree/cbindgen-issue

**Comment by emilio** [comment] 2020-09-21 06:49
Is this a regression?

**Comment by DevOrc** [comment] 2020-09-21 11:16
No - same issue on 0.14.4

**Comment by DevOrc** [comment] 2020-09-26 14:09
Here is a minimal test case:

```rust
pub type Foo = generic::Foo<u32>;

mod generic {
    pub struct Foo<T> {
        foo: T,
    }
}

mod structure {
    #[repr(C)]
    pub struct Foo{
        foo: u32
    }
}
```

Note this only panics when the language is set to C

**Comment by emilio** [comment] 2020-09-28 17:41
I see, I think that's "just" #7... We're probably getting confused about what of the two types we're referencing. We could potentially fail more gracefully here without much issue.

**Comment by emilio** [comment] 2020-10-13 10:00
Closing as a dupe of #7... You might want to `/// cbindgen:ignore` the generic type or such, I agree it's an unfortunate limitation.

**Closed by emilio** 2020-10-13 10:00 UTC
