### ISSUE TITLE
Broken self-referencing structs with C mode and style="type"

### ISSUE THREAD

**Issue by kvark** [eqrion/cbindgen#533] opened 2020-06-11 03:03 UTC
We are having trouble generating the header for this type in https://github.com/gfx-rs/wgpu-native/pull/34:
```rust
#[repr(C)]
pub struct ChainedStruct<'c> {
    next: Option<&'c ChainedStruct<'c>>,
    s_type: SType,
}
```

**Comment by emilio** [comment] 2020-06-11 13:11
Can you elaborate? That generates:

```c
struct ChainedStruct {
  const ChainedStruct *next;
  SType s_type;
};
```

Which is what I'd expect?

**Comment by cwfitzgerald** [comment] 2020-06-11 13:15
(I'm also part of the wgpu project)

The problem is that doesn't compile in C mode: https://godbolt.org/z/pNpTL8

It would have to generate

```cpp
struct ChainedStruct {
  const struct ChainedStruct *next;
  SType s_type;
};
```

in order to compile.

**Comment by emilio** [comment] 2020-06-12 17:55
Ah! I see... Can you output the whole configuration file you're using? I get what you expect with:

```
./target/debug/cbindgen t.rs --lang c --style tag
```

**Comment by cwfitzgerald** [comment] 2020-06-12 17:58
This is the config: https://github.com/gfx-rs/wgpu-native/blob/master/cbindgen.toml

https://github.com/gfx-rs/wgpu-native/pull/34 is the PR in question. Running `cbindgen -o ffi/wgpu.h` will generate the header (it's also checked into the repo.

**Comment by Korijn** [comment] 2020-06-18 11:27
It seems to me that the `style="tag"` is missing from the config.

**Comment by cwfitzgerald** [comment] 2020-06-25 23:14
So while `style="tag"` does fix the compilation error, I would still consider this a cbindgen issue, as while there's no way for `type` to deal with self referential structs in C mode, `both` should be able to deal with it, it just needs to know to generate references using the `tag` syntax.

**Comment by emilio** [comment] 2020-07-31 10:33
Yes, I agree that this is a cbindgen bug.

**Comment by emilio** [comment] 2020-11-26 10:06
I think https://github.com/eqrion/cbindgen/pull/615 should've fixed this... Now the question is whether the extra noise is worth it... @kvark / @cwfitzgerald can you confirm wgpu is fine with the bindings as generated with master even without `style = "tag"`?

**Closed by emilio** 2020-11-26 10:06 UTC
Labels: bug, help wanted
