### ISSUE TITLE
generic enums don't work great

### ISSUE THREAD

**Issue by jrmuizel** [eqrion/cbindgen#227] opened 2018-10-17 21:01 UTC
```rust
#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Debug, Hash)]
#[repr(C)]
pub enum ExternOption<T> {
    /// No value
    None,
    /// Some value `T`
    Some(T),
}

 #[no_mangle]
 pub extern "C" fn f() -> ExternOption<u32> {
     ExternOption::Some(3)
 }

```

gives:

```c++
#include <cstdint>
#include <cstdlib>

template<typename T>
struct ExternOption {
  enum class Tag {
    // No value
    None,
    // Some value `T`
    Some,
  };

  template<typename T>
  struct Some_Body {
    T _0;
  };

  Tag tag;
  union {
    Some_Body some;
  };
};

extern "C" {

ExternOption<uint32_t> f();

} // extern "C"

```

which doesn't build

```
out.cc:13:21: error: declaration of 'T' shadows template parameter
  template<typename T>
                    ^
out.cc:4:19: note: template parameter is declared here
template<typename T>
                  ^
out.cc:20:5: error: use of class template 'Some_Body' requires template
      arguments
    Some_Body some;
    ^
out.cc:14:10: note: template is declared here
  struct Some_Body {
         ^
out.cc:26:24: warning: 'f' has C-linkage specified, but returns incomplete type
      'ExternOption<uint32_t>' (aka 'ExternOption<unsigned int>') which could be
      incompatible with C [-Wreturn-type-c-linkage]
ExternOption<uint32_t> f();
                       ^
1 warning and 2 errors generated.
```

**Comment by emilio** [comment] 2018-10-17 21:02
Yeah, that's a dupe of #225. @eqrion maybe you could do a dot-release?

**Closed by emilio** 2018-10-17 21:02 UTC
