### ISSUE TITLE
Import renames à la `use Foo as Bar;` are not resolved properly

### ISSUE THREAD

**Issue by regexident** [eqrion/cbindgen#200] opened 2018-08-21 10:48 UTC
A minimalistic crate like this …

<details open>

```rust
// lib.rs

pub struct Foo { pub field: bool }

use Foo as Bar;

#[no_mangle]
pub unsafe extern "C" fn placebo(_bar: &Bar) {}
```

</details>

… generates a header like this …

<details open>

```c
// lib.h

#include <cstdint>
#include <cstdlib>

extern "C" {

void placebo(const Bar *_bar);

} // extern "C"
```

… emitting the following warning:

> WARN: Can't find `Bar`. This usually means that this type was incompatible or not found.

… while it should generate something like this instead:

<details open>

```c
// lib.h

#include <cstdint>
#include <cstdlib>

struct Foo;

extern "C" {

void placebo(const Foo *_bar);

} // extern "C"
```

</details>

### What's wrong:

1. cbindgen **doesn't recognize** that `Foo` is **used** in an exported `fn` thus **does not generate it**.
2. `_bar: &Bar` is not properly resolved to `_bar: &Foo` in the function argument.

### Observations:

1. This appears to be related to https://github.com/eqrion/cbindgen/issues/199.

Looks like cbindgen does not resolve scoped renames (i.e. `use Foo as Bar;`) of items.

**Comment by eqrion** [comment] 2018-08-21 18:45
This is a duplicate of the root issue of #7. Essentially `cbindgen` doesn't understand fully qualified names, and it doesn't understand imports and aliases. This is a longstanding issue, unfortunately.

I'll close this here. If you'd provide some of these details in that issue, I'd greatly appreciate that.

**Closed by eqrion** 2018-08-21 18:45 UTC
