### ISSUE TITLE
Struct definition in local dependency isn't found

### ISSUE THREAD

**Issue by acfoltzer** [eqrion/cbindgen#292] opened 2019-02-20 20:37 UTC
I checked in a small example here: https://github.com/acfoltzer/cbindgen-dep

I have a dependency crate `dep` that defines a struct `dep_struct`, and the root crate uses that struct in an extern, no_mangle function.

I am running `cbindgen` via the `build.rs` of the root crate, and would expect the definition of `dep_struct` to appear in the generated bindings. However I just get the prototype of the extern function without even an opaque definition of `dep_struct`.

I'm not sure whether this is a bug, or I'm just configuring `cbindgen` wrong, but it sounds like others have been successful with this in the past?

**Comment by acfoltzer** [comment] 2019-02-21 18:07
I've added a variant that shows similar behavior with just a single crate: https://github.com/acfoltzer/cbindgen-dep/tree/single-crate

It appears that if the struct definition is more than one module away from where it is used in a function definition, the struct definition is omitted from the bindings. This now definitely seems like a bug :slightly_smiling_face:

**Comment by karroffel** [comment] 2019-02-22 14:38
I ran into the same problem. It seems like cbindgen is not working properly yet with Rust 2018.

Once I declared the dependency with `extern crate name;` it worked.

This should probably be fixed, but it's a workaround.

**Comment by vmx** [comment] 2019-08-09 12:59
I think this issue can be closed. I can't reproduce it (neither of the two cases above) with neither cbindgen 0.8.6 nor 0.9.0.

**Comment by emilio** [comment] 2019-08-10 16:36
Yup, this was fixed by #332

**Closed by emilio** 2019-08-10 16:36 UTC
