### ISSUE TITLE
Functions with libc types are skipped

### ISSUE THREAD

**Issue by brendanzab** [eqrion/cbindgen#51] opened 2017-09-04 07:11 UTC
If I have a function with a type from libc like `libc::c_uchar`:

```rust
extern crate libc;

#[no_mangle]
pub extern "C" fn allsorts_lookup_glyph_index(subtable: *mut libc::c_uchar, char_code: u32) -> u32 {
    abort_on_panic(move || unimplemented!())
}
```

cbindgen will produce an empty header:

```c
/* Generated with cbindgen:0.1.23 */

#include <cstdint>
#include <cstdlib>

extern "C" {

} // extern "C"
```

where as using `u32` causes the function prototype to be output:

```rust
extern crate libc;

#[no_mangle]
pub extern "C" fn allsorts_lookup_glyph_index(subtable: *mut u32, char_code: u32) -> u32 {
    abort_on_panic(move || unimplemented!())
}
```

```c
/* Generated with cbindgen:0.1.23 */

#include <cstdint>
#include <cstdlib>

extern "C" {

uint32_t allsorts_lookup_glyph_index(uint32_t *subtable, uint32_t char_code);

} // extern "C"
```

**Comment by eqrion** [comment] 2017-09-05 14:45
Currently we hardcode the libc types into cbindgen [here](https://github.com/eqrion/cbindgen/blob/master/src/bindgen/ir/ty.rs#L52).

Unfortunately the support for explicit/full paths isn't very good, #7, so when the path is `libc::c_char` cbindgen misses it. You can get around this, like you saw, by using a `use` item.

**Comment by eqrion** [comment] 2017-10-10 02:59
@brendanzab Could you recheck this again and see if the problem is still around?

I landed some code related to this just now. It's not in the latest crate, so you'd have to check with the master branch.

**Comment by eqrion** [comment] 2018-08-18 05:12
I'm going to close this now due to inactivity. Feel free to re-open if this is still an issue.

**Closed by eqrion** 2018-08-18 05:12 UTC
Labels: bug
