### ISSUE TITLE
Infinite compile times when using expand

### ISSUE THREAD

**Issue by mmstick** [eqrion/cbindgen#121] opened 2018-01-29 19:41 UTC
Have some functions being generated via macros:

```rust
macro_rules! disk_apply {
    ($disk_name:ident, $(
        $(#[$attr:meta])*
        $fn:ident($($name:ident: $type:ty),*) $action:block
    )*) => (
        $(
            #[no_mangle]
            $(#[$attr])*
            /// # Errors
            /// On error, -1 will be returned, otherwise 0.
            pub unsafe extern "C" fn $fn(
                $disk_name: *mut DistinstDisk,
                $($name: $type),*
            ) -> libc::c_int {
                disk_action_mut($disk_name, |$disk_name| $action.ok().map_or(-1, |_| 0))
            }
        )*
    );
}

disk_apply!(disk,
    /// Adds a new partition to the disk's partition scheme, using a PartitionBuilder object.
    distinst_disk_add_partition(partition: *mut DistinstPartitionBuilder) {
        disk.add_partition(*Box::from_raw(partition as *mut PartitionBuilder))
    }

    /// Removes an existing partition from the disk, via the partition's ID.
    distinst_disk_remove_partition(partition: libc::c_int) {
        disk.remove_partition(partition)
    }

    /// Resizes an existing partition on the disk, to the new length specified.
    distinst_disk_resize_partition(partition: libc::c_int, length: libc::uint64_t) {
        disk.resize_partition(partition, length)
    }

    /// Moves an existing partition on the disk, to the new start sector specified.
    distinst_disk_move_partition(partition: libc::c_int, start: libc::uint64_t) {
        disk.move_partition(partition, start)        
    }

    /// Formats an existing partition using the file system specified.
    distinst_disk_format_partition(partition: libc::c_int, fs: DISTINST_FILE_SYSTEM_TYPE) {
        let fs = match Option::<FileSystemType>::from(fs) {
            Some(fs) => fs,
            None => {
                info!("file system type required");
                return -1;
            }
        };

        disk.format_partition(partition, fs)
    }

    /// Clobbers all partitions on the disk, and writes a new partition table.
    distinst_disk_mklabel(table: DISTINST_PARTITION_TABLE) {
        let table = match table {
            DISTINST_PARTITION_TABLE::GPT => PartitionTable::Gpt,
            DISTINST_PARTITION_TABLE::MSDOS => PartitionTable::Msdos,
            _ => return -1,
        };

        disk.mklabel(table)
    }

    /// Commits all changes to the disk
    distinst_disk_commit() {
        disk.commit()
    }
);
```

, and so I've defined the following in the `cbindgen.toml`:

```toml
include_guard = "distinst_h"
language = "C"

[parse]
parse_deps = false
expand = ["distinst"]

[enum]
prefix_with_name = true
```

For a project with this configuration:

```toml
[package]
name = "distinst"
version = "0.3.1"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"
build = "build.rs"
readme = "README.md"

[lib]
name = "distinst"
crate-type = ["lib", "dylib"]

[build-dependencies]
cbindgen = "0.4"

[dependencies]
clap = "=2.26.0"
libc = "0.2"
libparted = "0.1.2"
log = "0.3"
pbr = "1.0"
tempdir = "0.3"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]

[dependencies.failure_derive]
version = "0.1.1"
```

Along with the following in `build.rs`:

```rust
extern crate cbindgen;

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn generate_dylib_bindings() {
    let target_path = PathBuf::from("target");

    let pkg_config = format!(
        include_str!("distinst.pc.in"),
        name = env::var("CARGO_PKG_NAME").unwrap(),
        description = env::var("CARGO_PKG_DESCRIPTION").unwrap(),
        version = env::var("CARGO_PKG_VERSION").unwrap()
    );

    fs::create_dir_all(target_path.join("pkgconfig")).unwrap();
    fs::File::create(target_path.join("pkgconfig").join("distinst.pc.stub"))
        .unwrap()
        .write_all(&pkg_config.as_bytes())
        .unwrap();

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::generate(crate_dir)
        .expect("unable to generate bindings")
        .write_to_file(target_path.join("include").join("distinst.h"));
}

fn main() {
    // NOTE: Comment this out when developing.
    generate_dylib_bindings();
}
```

When building the project (`cargo build`), I'm getting this error:

```
thread 'main' panicked at 'unable to generate bindings: CargoExpand("distinst", Compile("error: extra arguments to `rustc` can only be passed to one target, consider filtering\nthe package by passing e.g. `--lib` or `--bin NAME` to specify a single target\n"))', libcore/result.rs:945:5
```

**Comment by eqrion** [comment] 2018-01-29 21:22
I think adding `--lib` to the cargo expand command line will fix this. I added this in `0.4.2`. Let me know if it doesn't work for you.

**Comment by mmstick** [comment] 2018-01-29 21:51
Not quite sure what's happening, but it's been building for more than 15 minutes now, when it normally only takes a handful of seconds on this quad core i7 w/ HT & a SSD.

**Comment by eqrion** [comment] 2018-01-29 21:54
Is the first time using `expand`? Unfortunately `expand` requires using `rustc` which can take a long time.

**Comment by mmstick** [comment] 2018-01-29 21:57
Without expand, it builds within ~5 seconds (but also doesn't generate header details for all the macro-generated functions). With it, it's still going. May just have to give up on the idea of simplifying the C API for distinst with macros.

**Comment by eqrion** [comment] 2018-01-29 21:59
How long does the crate normally take to compile with `rustc`? It could be a bug because 15 minutes sounds excessive..

**Comment by mmstick** [comment] 2018-01-29 22:17
With `cargo clean && cargo rustc --lib` & expand disabled

```
Finished dev [unoptimized + debuginfo] target(s) in 65.75 secs
```

With `cargo clean && cargo build --lib` with expand enabled

```
... still waiting
```

**Comment by mmstick** [comment] 2018-01-29 23:01
After 30 minutes passed, I gave up on compiling.

**Comment by mmstick** [comment] 2018-05-08 18:58
Confirming that this continues to happen in `0.6.0` with both the CLI cbindgen and the `build.rs` equivalent. Although, interestingly, the behavior I'm getting is that eventually CPU usage goes down to 0, but it remains stuck regardless.

**Comment by mmstick** [comment] 2018-05-08 19:04
May be tested against this branch of distinst: https://github.com/pop-os/distinst/tree/ffi-macros

```
cargo build --release --manifest-path ffi/Cargo.toml
```

**Comment by vmx** [comment] 2019-08-17 15:29
This works on cbindgen master. Probably fixed by https://github.com/eqrion/cbindgen/pull/371. Thanks @mmstick for providing an easy to reproduce example, so that it can quickly be checked if things are fixed.

This issue can be closed.

**Comment by emilio** [comment] 2019-08-17 19:30
Yup, thanks for the fix!

**Closed by emilio** 2019-08-17 19:30 UTC
