### ISSUE TITLE
Rust reserved identifiers are not renamed

### ISSUE THREAD

**Issue by morrisonlevi** [eqrion/cbindgen#692] opened 2021-06-15 19:50 UTC
If a struct uses a rust reserved identifier like `type`, it doesn't get renamed. For example:

```rust
use std::ffi::c_int;

#[repr(C)]
pub struct Identifier {
  pub r#type: c_int,
}

#[no_mangle]
pub extern "C" fn identify(id: Identifier) {}
```

Result of `cbindgen --lang c tmp.rs`:

```c
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Identifier {
  int r#type;
} Identifier;

void identify(struct Identifier id);
```

The line with `int r#type;` isn't valid C; it probably should be `int type`. In general, `r#thing` should become `thing` unless `thing` also a C reserved identifier, and then it should become `thing_`.

**Comment by emilio** [comment] 2021-06-16 08:29
This is a dupe of #410 (just in a member name rather than a function name).

**Closed by emilio** 2021-06-16 08:29 UTC
