### ISSUE TITLE
'pub enum' doesn't exported

### ISSUE THREAD

**Issue by RazrFalcon** [eqrion/cbindgen#33] opened 2017-07-22 13:04 UTC
Looks like only "used" enums are exported.

**Comment by rlhunt** [comment] 2017-07-22 15:55
This is by design right now. We filter out all items that aren't used by an extern "C" function. This makes the output headers smaller.

I'd like to make this configurable so that everything can be exported. But I haven't yet.

**Comment by hfiguiere** [comment] 2017-09-25 22:20
actual enums repr(i32) required by export functions are exported as struct (forward) which is both incorrect and not useful.

**Comment by eqrion** [comment] 2017-09-27 07:20
@hfiguiere That is because cbindgen doesn't recognize `repr(i32)` for enum's. That is fixed in 9ff9ab16e26bffb3cd69148572d6541f8c9fb535.

**Comment by hfiguiere** [comment] 2017-09-27 20:36
that works. Thanks!

**Closed** 2017-11-14 07:14 UTC
Labels: enhancement

**Comment by elichai** [comment] 2018-11-14 14:19
Is this still true? @eqrion 
I have a rust file with just `#[repr(C)]` enums without any `extern "C"` functions.
Is there a way to make it work or I must create dumb functions just so it will work on the enums?

**Comment by emilio** [comment] 2018-11-15 16:59
You can use the `export.include` configuration option.

**Comment by elichai** [comment] 2018-11-18 08:49
It worked. Thanks!
